name: functional test

on:
  push:
    branches: [ test-branch ]

jobs:
  functional_test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get source code for collecting coverage
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install coverage

    - name: Run the functional tests and collect the coverage
      run: sh .github/workflows/cov.sh

